### ISSUE TITLE
"Failed to get WowUp update" error message

### ISSUE THREAD

**Issue by Eldranil** [WowUp/WowUp.CF#10]
**Describe the bug**
The client sends a "failed update" error when checking for update.

**To Reproduce**
1. Open WowUp-CF
2. Click on the "Check for Update" button on the bottom right.
3. See error pop-up at the bottom of the software window (see screenshot below).

**Expected behavior**
In this case I believe my client is up to date, so instead of throwing an error, it should say something along the lines of "Current version is already up to date" or "No update yet".

**Screenshots**
![image](https://user-images.githubusercontent.com/117493259/200946317-1904aa56-5e28-4cf1-87a8-ec73f230b205.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: N/A (Client)
 - Version 2.9.1-beta8 CF

**Comment by jliddev** [comment]
This should now be resolved.
