### ISSUE TITLE
Will the work from this fork be merged into master project?

### ISSUE THREAD

**Issue by Gigas002** [WowUp/WowUp.CF#12]
Sorry I have to ask a question through issues, but I didn't find any messages about it in this repo. I'm interested, if this fork be merged into [WowUp](https://github.com/WowUp/WowUp), or will be a separate project? I'm maintaining the AUR's `wowup-bin` package, and just wondering, if I should create a new package for this repo, or it'll be merged someday.

**Comment by cremor** [comment]
The reason for the separate app is explained here: https://www.patreon.com/posts/next-thing-74232257

**Comment by Gigas002** [comment]
Thanks for explanation! :+1:
