### ISSUE TITLE
Detection of addons

### ISSUE THREAD

**Issue by Addonman** [WowUp/WowUp.CF#13]
Seems Cf version doesnt recognize addon version installed properly. I update addons with WOWup ,then with Cursforge own app and then i use WOWup CF version. Result of that version is that  ican update3 like 90+ addons when i know that i already have most up to date versions of that addon installed. That result doesnt seems to be ok.

**Comment by jliddev** [comment]
Changing/Installing addons with other apps is not recommended. If you insist then you'll need to do a re-scan when you do so otherwise the app will not be aware of the changes.
