### ISSUE TITLE
Leaving WoWUp and why

### ISSUE THREAD

**Issue by tflo** [WowUp/WowUp.CF#38]
Really sad to say that I have to abandon WoWUp and WoWUp-CF for the time being.

Main reasons:

- Crucial functionality not implemented;
	- No way to list new or recently updated addons, if they aren't in the "favorized" bracket. So, effectively, no way to get new addons or info on new addons at all via listing. This is a showstopper. See various issue threads on that. 
	- Changed addons (eg. addons fixed by DIY) are no longer listed among updates, if an update is published. This is, if I mod a mod, I'm out of notification.This is a showstopper. Why? Even if I have modded the addon, usually I aim to maintain a modded version relative to the source (aka 'fork'), but for that I have to know in first place that there is a new version of the source, no? See also https://github.com/WowUp/WowUp/issues/197 . 
- Main reason for not using Overwolf stuff was to avoid unwanted data collection and usage. 
  - Well, the thing that happened with my first WoWUp run was that my outgoing firewall told me that WoWUp was trying to connect to Google (can be disabled in the prefs). If there is anything worse than Overwolf than it is Google. So, really?, or were you just joking with some kind of very weird sarcastic trolling sort of morbid humour? If you go Google, folks, then there is no reason to not go Overwolf. And then there is no reason, for us users, to use WoWUp.
- You know, GA isn't the only way to get data? (If you're goin to tell me that alternatives will be too expensive , you are simply malinformed.)
- I also chatted with a person on their Discord about possibilities to publish new addons w/o the need of contacting WoWUp each time, and they offered me a Google solution. Scrap it. Really? Google Doc or spreadsheet? These guys are ... well just skip'em. No clue in which world they are currently in. Sorry for the harsh words, but... once again there are solutions that do not involve interactions with criminal entities..
- -  Stupid minor stuff like [this](https://github.com/WowUp/WowUp.CF/issues/33), not really important, but QoL-important.Just mentioning for the case that the above issues aren't enough 🤐

I really would have loved to see this project florish. Good luck.

– Tom

PS: And yes, I'm salty and a little angry that you didn't take your chance. It might have been great.

**Comment by linaori** [comment]
You're welcome to donate money for development time if this free tool isn't up to your standards.
