### ISSUE TITLE
[v2.9.1-beta.9] Reinstall option missing for Curse addons

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp.CF#7]
v2.9.1-beta.9

Curse Addon:
![image](https://user-images.githubusercontent.com/1754678/200784331-e147727c-6218-4534-82e9-8bc89bb56987.png)

Hub Addon:
![image](https://user-images.githubusercontent.com/1754678/200784383-c49217bd-b2a3-48c6-bb7f-233a7d59f95b.png)

**Comment by jliddev** [comment]
This should be resolved as of beta 12
