### ISSUE TITLE
last tab in addon popup not remembered

### ISSUE THREAD

**Issue by Daeveren** [WowUp/WowUp.CF#9]
The popup that shows up when clicking an addon in the list does not remember the last tab.
In normal WowUp, once I visited the Changelog tab of an addon, everytime I'd open addon popups it would directly show the Changelog tab. Now the tab always defaults to Description, which is rather useless for the already installed addons.

Same behavior in beta 8, 9 and 10

**Comment by jliddev** [comment]
Do you have this option enabled in the application settings? 
![image](https://user-images.githubusercontent.com/20467484/201111314-8aefceda-7109-437e-95e0-f1585f6d36de.png)

**Comment by Daeveren** [comment]
I didn't had it, was not aware it was a toggle.
Apologise for wasting your time. Closing this.
